import { useState } from "react";
import { useParams } from "react-router-dom";
import { httpsCallable } from "firebase/functions";

import { functions } from "../lib/firebase";
import { PageHeader } from "../components/shared/PageHeader";
import { Card, CardContent } from "../components/ui/card";
import { Button } from "../components/ui/button";
import { StatusBadge } from "../components/shared/StatusBadge";
import { ReportViewer } from "../components/reports/ReportViewer";

export function ReportDetailPage() {
  const { reportId } = useParams();
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const [loadingShare, setLoadingShare] = useState(false);

  const mockReport = {
    id: reportId ?? "report",
    title: "Bias Research Report",
    generatedAt: "2026-04-20 14:30",
    generatedBy: "Asha Verma (Compliance)",
    analysisId: "analysis-001",
    type: "Bias Research",
    status: "ready",
    sha256Hash: "a5b4c3d2e1f0987654321deadbeef",
    pdfUrl: "https://example.com/report.pdf"
  };

  const handleShare = async () => {
    setLoadingShare(true);
    try {
      const generateFn = httpsCallable(functions, "generateReportShareUrl");
      const result = await generateFn({ reportId: mockReport.id });
      const url = (result.data as { url: string }).url;
      setShareUrl(url);
      await navigator.clipboard.writeText(url);
    } catch {
      setShareUrl("Unable to generate share link.");
    } finally {
      setLoadingShare(false);
    }
  };

  return (
    <div className="space-y-8">
      <PageHeader
        title={mockReport.title}
        description="Full compliance narrative and remediation plan."
        breadcrumbs={[{ label: "Kohei" }, { label: "Reports" }, { label: reportId ?? "Report" }]}
      />

      <Card>
        <CardContent className="space-y-4 py-6">
          <div className="flex flex-wrap items-center justify-between gap-4">
            <div>
              <p className="text-xs uppercase tracking-[0.3em] text-[var(--muted)]">Report metadata</p>
              <h2 className="mt-2 text-2xl font-semibold">{mockReport.title}</h2>
            </div>
            <StatusBadge tone="success" label={mockReport.type} />
          </div>
          <div className="grid gap-3 text-sm text-[var(--muted)] md:grid-cols-2">
            <p>Generated: {mockReport.generatedAt}</p>
            <p>Generated by: {mockReport.generatedBy}</p>
            <p>Analysis ID: {mockReport.analysisId}</p>
            <p>SHA-256: {mockReport.sha256Hash}</p>
          </div>
          <div className="flex flex-wrap gap-3">
            <Button asChild>
              <a href={mockReport.pdfUrl} download>
                Download PDF
              </a>
            </Button>
            <Button variant="secondary" onClick={handleShare} disabled={loadingShare}>
              {loadingShare ? "Sharing..." : "Share"}
            </Button>
            <Button variant="outline">Regenerate</Button>
            <Button variant="ghost">Archive</Button>
          </div>
          {shareUrl && <p className="text-xs text-[var(--muted)]">Share link copied: {shareUrl}</p>}
        </CardContent>
      </Card>

      <ReportViewer url={mockReport.pdfUrl} />
    </div>
  );
}
